/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author erick
 */

public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        
        jTextField3.setDocument(new LimiteCaracteres(10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TeclaCero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TeclaPunto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TeclaIgual = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TeclaMas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Nueve = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Ocho = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Siete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Cuatro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Cinco = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Seis = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Uno = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Dos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Borrar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TeclaMC = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Tres = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TeclaMMas = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        TeclaMenos = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TeclaPor = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TeclaEntre = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeclaCero.setBackground(new java.awt.Color(4, 20, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaCeroLayout = new javax.swing.GroupLayout(TeclaCero);
        TeclaCero.setLayout(TeclaCeroLayout);
        TeclaCeroLayout.setHorizontalGroup(
            TeclaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaCeroLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaCeroLayout.setVerticalGroup(
            TeclaCeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaCeroLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 70, 70));

        TeclaPunto.setBackground(new java.awt.Color(4, 20, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaPuntoLayout = new javax.swing.GroupLayout(TeclaPunto);
        TeclaPunto.setLayout(TeclaPuntoLayout);
        TeclaPuntoLayout.setHorizontalGroup(
            TeclaPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaPuntoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaPuntoLayout.setVerticalGroup(
            TeclaPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaPuntoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 530, 70, 70));

        TeclaIgual.setBackground(new java.awt.Color(35, 150, 140));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("=");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 70));

        javax.swing.GroupLayout TeclaIgualLayout = new javax.swing.GroupLayout(TeclaIgual);
        TeclaIgual.setLayout(TeclaIgualLayout);
        TeclaIgualLayout.setHorizontalGroup(
            TeclaIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaIgualLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaIgualLayout.setVerticalGroup(
            TeclaIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaIgualLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 530, 142, 70));

        TeclaMas.setBackground(new java.awt.Color(10, 65, 70));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("+");
        jLabel15.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaMasLayout = new javax.swing.GroupLayout(TeclaMas);
        TeclaMas.setLayout(TeclaMasLayout);
        TeclaMasLayout.setHorizontalGroup(
            TeclaMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMasLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaMasLayout.setVerticalGroup(
            TeclaMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMasLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 458, 70, 70));

        Nueve.setBackground(new java.awt.Color(4, 20, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("9");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout NueveLayout = new javax.swing.GroupLayout(Nueve);
        Nueve.setLayout(NueveLayout);
        NueveLayout.setHorizontalGroup(
            NueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(NueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NueveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        NueveLayout.setVerticalGroup(
            NueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(NueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NueveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(Nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 458, 70, 70));

        Ocho.setBackground(new java.awt.Color(4, 20, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("8");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout OchoLayout = new javax.swing.GroupLayout(Ocho);
        Ocho.setLayout(OchoLayout);
        OchoLayout.setHorizontalGroup(
            OchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OchoLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OchoLayout.setVerticalGroup(
            OchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OchoLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 458, 70, 70));

        Siete.setBackground(new java.awt.Color(4, 20, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("7");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout SieteLayout = new javax.swing.GroupLayout(Siete);
        Siete.setLayout(SieteLayout);
        SieteLayout.setHorizontalGroup(
            SieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SieteLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SieteLayout.setVerticalGroup(
            SieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SieteLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 458, 70, 70));

        Cuatro.setBackground(new java.awt.Color(4, 20, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("4");
        jLabel9.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout CuatroLayout = new javax.swing.GroupLayout(Cuatro);
        Cuatro.setLayout(CuatroLayout);
        CuatroLayout.setHorizontalGroup(
            CuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuatroLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CuatroLayout.setVerticalGroup(
            CuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuatroLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 386, 70, 70));

        Cinco.setBackground(new java.awt.Color(4, 20, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("5");
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout CincoLayout = new javax.swing.GroupLayout(Cinco);
        Cinco.setLayout(CincoLayout);
        CincoLayout.setHorizontalGroup(
            CincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CincoLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CincoLayout.setVerticalGroup(
            CincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CincoLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 386, 70, 70));

        Seis.setBackground(new java.awt.Color(4, 20, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("6");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout SeisLayout = new javax.swing.GroupLayout(Seis);
        Seis.setLayout(SeisLayout);
        SeisLayout.setHorizontalGroup(
            SeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeisLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SeisLayout.setVerticalGroup(
            SeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeisLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 386, 70, 70));

        Uno.setBackground(new java.awt.Color(4, 20, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("1");
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 70));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UnoLayout = new javax.swing.GroupLayout(Uno);
        Uno.setLayout(UnoLayout);
        UnoLayout.setHorizontalGroup(
            UnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        UnoLayout.setVerticalGroup(
            UnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 314, 70, 70));

        Dos.setBackground(new java.awt.Color(4, 20, 25));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("2");
        jLabel11.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout DosLayout = new javax.swing.GroupLayout(Dos);
        Dos.setLayout(DosLayout);
        DosLayout.setHorizontalGroup(
            DosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DosLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DosLayout.setVerticalGroup(
            DosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DosLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 314, 70, 70));

        Borrar.setBackground(new java.awt.Color(4, 20, 25));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("C");
        jLabel16.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout BorrarLayout = new javax.swing.GroupLayout(Borrar);
        Borrar.setLayout(BorrarLayout);
        BorrarLayout.setHorizontalGroup(
            BorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BorrarLayout.setVerticalGroup(
            BorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 242, 70, 70));

        TeclaMC.setBackground(new java.awt.Color(4, 20, 25));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("MC");
        jLabel17.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaMCLayout = new javax.swing.GroupLayout(TeclaMC);
        TeclaMC.setLayout(TeclaMCLayout);
        TeclaMCLayout.setHorizontalGroup(
            TeclaMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMCLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaMCLayout.setVerticalGroup(
            TeclaMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMCLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 242, 70, 70));

        Tres.setBackground(new java.awt.Color(4, 20, 25));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("3");
        jLabel12.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TresLayout = new javax.swing.GroupLayout(Tres);
        Tres.setLayout(TresLayout);
        TresLayout.setHorizontalGroup(
            TresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TresLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TresLayout.setVerticalGroup(
            TresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TresLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 314, 70, 70));

        TeclaMMas.setBackground(new java.awt.Color(4, 20, 25));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("M+");
        jLabel18.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaMMasLayout = new javax.swing.GroupLayout(TeclaMMas);
        TeclaMMas.setLayout(TeclaMMasLayout);
        TeclaMMasLayout.setHorizontalGroup(
            TeclaMMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMMasLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaMMasLayout.setVerticalGroup(
            TeclaMMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMMasLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaMMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 242, 70, 70));

        TeclaMenos.setBackground(new java.awt.Color(10, 65, 70));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("-");
        jLabel14.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaMenosLayout = new javax.swing.GroupLayout(TeclaMenos);
        TeclaMenos.setLayout(TeclaMenosLayout);
        TeclaMenosLayout.setHorizontalGroup(
            TeclaMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMenosLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaMenosLayout.setVerticalGroup(
            TeclaMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaMenosLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 386, 70, 70));

        TeclaPor.setBackground(new java.awt.Color(10, 65, 70));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("x");
        jLabel13.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaPorLayout = new javax.swing.GroupLayout(TeclaPor);
        TeclaPor.setLayout(TeclaPorLayout);
        TeclaPorLayout.setHorizontalGroup(
            TeclaPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaPorLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaPorLayout.setVerticalGroup(
            TeclaPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaPorLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 314, 70, 70));

        TeclaEntre.setBackground(new java.awt.Color(10, 65, 70));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(".");
        jLabel19.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout TeclaEntreLayout = new javax.swing.GroupLayout(TeclaEntre);
        TeclaEntre.setLayout(TeclaEntreLayout);
        TeclaEntreLayout.setHorizontalGroup(
            TeclaEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaEntreLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TeclaEntreLayout.setVerticalGroup(
            TeclaEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeclaEntreLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(TeclaEntre, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 242, 70, 70));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setBorder(null);
        jTextField2.setDragEnabled(true);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, -1));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setBorder(null);
        jTextField3.setDragEnabled(true);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jTextField3.setCaretPosition(0);
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borrar;
    private javax.swing.JPanel Cinco;
    private javax.swing.JPanel Cuatro;
    private javax.swing.JPanel Dos;
    private javax.swing.JPanel Nueve;
    private javax.swing.JPanel Ocho;
    private javax.swing.JPanel Seis;
    private javax.swing.JPanel Siete;
    private javax.swing.JPanel TeclaCero;
    private javax.swing.JPanel TeclaEntre;
    private javax.swing.JPanel TeclaIgual;
    private javax.swing.JPanel TeclaMC;
    private javax.swing.JPanel TeclaMMas;
    private javax.swing.JPanel TeclaMas;
    private javax.swing.JPanel TeclaMenos;
    private javax.swing.JPanel TeclaPor;
    private javax.swing.JPanel TeclaPunto;
    private javax.swing.JPanel Tres;
    private javax.swing.JPanel Uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
